### ISSUE TITLE
kafka_consumer_group_offset missing

### ISSUE THREAD

**Issue by ulutomaz** [braedon/prometheus-kafka-consumer-group-exporter#17]
Hi, 

i've installed the tool, it works except i don't have any of the metrics kafka_consumer_group_offset in prometheus? 

Any idea?

Best,
Tomaz

**Comment by jsargiot** [comment]
Have you tried using `curl` to access directly the exporter endpoint? Do you see the kafka_consumer_group_offset metrics that way?

**Comment by ulutomaz** [comment]
I did tried to use curl. And there is no kafka_consumer* metrics. Only the others.

**Comment by jsargiot** [comment]
> I did tried to use curl. And there is no kafka_consumer* metrics. Only the others.

Which others? Can you paste the output of curl?

Also, is there any error in the logs?

**Comment by tomazbracic** [comment]
As i am not at computer at the moment, but with oters i mean all other metrics whic don't start with kafka_consumer..... I believe others are high and low watermark or something.

**Comment by jutley** [comment]
Are you using the old consumers that store offsets in Zookeeper? I don't think those offsets will be available via this tool.

**Comment by braedon** [comment]
Hi @ulutomaz, first thing to check (as @jutley mentioned) is if your consumers are storing their offsets in Zookeeper, or in Kafka. This exporter only works with Kafka offset storage, as it consumes the `__consumer_offsets` topic to get the offsets.

You will also only get offsets for consumers that are actively committing their offsets. By default, only new offset commit messages are consumed - old offsets aren't read. You can use the `--from-start` argument to tell the exporter to read all the existing offset commits - note that it will take some time to catch up, so this option isn't recommended for production.

**Comment by ulutomaz** [comment]
No, it should be in Kafka, not in Zookeeper. Will check `--from-start`.

**Comment by braedon** [comment]
Assuming this is sorted - feel free to re-open if not!
