### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by jutley** [braedon/prometheus-kafka-consumer-group-exporter#18]
I've noticed that memory usage consistently increases over time, until our containers eventually OOM and start over.

We are not generating more metrics over time, as shown, so it seems strange that memory would grow so consistently.

I don't have many details, but my org did observe that 4 different pods started at the same time and crashed at the same time, over a week later. The pods are in different Kubernetes clusters, reading from different Kafka clusters with drastically different throughput. So I don't think this has anything to do with throughput on the `__consumer_offsets` topic. 

![image](https://user-images.githubusercontent.com/5660346/45768630-46da6e00-bbf2-11e8-8365-4b93b455ecaa.png)

**Comment by braedon** [comment]
This was due to a bug in the Prometheus client and python 3.7. The client has been patched, so I'll upgrade to the new version, which should fix the issue.

**Comment by braedon** [comment]
@jutley fixed in [0.5.0](https://github.com/braedon/prometheus-kafka-consumer-group-exporter/releases/tag/0.5.0)
