### ISSUE TITLE
Port number mismatch

### ISSUE THREAD

**Issue by jrnt30** [braedon/prometheus-kafka-consumer-group-exporter#2]
First, thanks for the project!  The current documentation states using `9028` for the bound port, however the `Release` and the pushed `0.1.0` Docker image are still bound to `:8080`. 

There should be a new release cut for the 0.2.x version so the docs & releases are in sync.

**Comment by braedon** [comment]
Good point! I was holding off releasing 0.2 until I have a couple of features done, but haven't been able to work on them for a while. I'll sort something out soon.
