### ISSUE TITLE
Kafka consumer group lag is occasionally below zero

### ISSUE THREAD

**Issue by weeco** [braedon/prometheus-kafka-consumer-group-exporter#21]
On some partitions the exporter shows a slightly negative lag (something between 0 and -30). I am aware that you have to calculate the lag by subtracting the current offset from the high watermark and I could imagine that either the high watermark is slightly behind in your calculations.

Maybe you could set the lag to 0 if the lag is negative, as a negative lag doesn't make any sense?

**Comment by Matzz** [comment]
We see this issue quite frequently for multiple partitions. Lag sometimes reach -300 per partition.
We use quite old Kafka - 0.11 but we are planning to upgrade it soon. I'll let you know if it still an issue in a newer version.

**Comment by weeco** [comment]
@matzz the issue will still persist. I am running Kafka 2.1.1 and the problem exists because the partition high watermark is not necessarily up to date in contrast to the consumer group offset. Therefore the consumer offset can be higher than the partition high watermark.

It seems like this exporter is not maintained anymore, hence I am currently writing my own Kafka exporter, written in go with more features

**Comment by maulikjs** [comment]
@weeco hey did you start working on the client?
Maybe we can collaborate on this. I am facing the exact same problem right now

**Comment by weeco** [comment]
@maulikjs Yea I already started and any help is absolutely welcome. I can help you to get started with the code.

This is the repository: https://github.com/google-cloud-tools/kafka-minion

On master there is a "simple" version, which however causes broker timeouts on mid+ sized clusters when you query consumer offsets. Hence I am rewriting it in a branch, where it gets the consumer offsets from the __consumer_offsets topic. I should be done with it on sunday and I'll write a small readme for contributors.

**Comment by maulikjs** [comment]
@weeco 
Awesome thanks, ill look into this and then we can take it from there!

**Comment by braedon** [comment]
@weeco Sorry for the lack of reply on this (and other issues) - life has been super busy over the last 6 months!

Things are settling down, so I'll get back to maintaining this project soon.

**Comment by braedon** [comment]
@weeco fixed in [0.5.0](https://github.com/braedon/prometheus-kafka-consumer-group-exporter/releases/tag/0.5.0)
