### ISSUE TITLE
[Feature Request] Add in additional metric for Consumer Lag

### ISSUE THREAD

**Issue by jrnt30** [braedon/prometheus-kafka-consumer-group-exporter#3]
While the offset of CGs is useful, add in an additional metric around the CG's lag would be extremely beneficial for gauging the health of the CG in conjunction with the Commit metric being published.

**Comment by braedon** [comment]
I'm part way though implementing a high-water mark metric, which will allow you to compute the lag. Not sure when I'll have a chance to finish it, but it is coming...
