### ISSUE TITLE
kafka_consumer_group_exporter_lag == 1 when fully caught up

### ISSUE THREAD

**Issue by jutley** [braedon/prometheus-kafka-consumer-group-exporter#32]
When the exporter is fully caught up, the lag reports as 1 instead of 0.

Topic highwaters are the offset where the next message will be written. Since the exporter is subtracting the most recently read message, this will result in a difference of 1.

We don't see this for the normal lag metric because consumer groups commit the offset they should begin reading from, similar to topics.

**Comment by braedon** [comment]
Fixed in [0.5.3](https://github.com/braedon/prometheus-kafka-consumer-group-exporter/releases/tag/0.5.3)
