### ISSUE TITLE
Should make new release with kafka-python v2.0.0+ (SASL/SCRAM auth support missing)

### ISSUE THREAD

**Issue by AkselAllas** [braedon/prometheus-kafka-consumer-group-exporter#41]
I basically ran into this exact SO problem: https://stackoverflow.com/questions/57290708/setting-python-kafkaproducer-sasl-mechanism-property

I couldn't set SCRAM-SHA-512 as sasl_mechanism
![image](https://user-images.githubusercontent.com/26136082/115107862-0ee86280-9f76-11eb-9601-862dd4af6a43.png)

I solved it by building the image myself and then It worked, since It pulled the newer kafka-python v2.0.0+ version.

**Comment by braedon** [comment]
Thanks for reporting this @AkselAllas. I've pushed a re-built docker image to the `0.5.5` tag.

In case one of the dependency updates has broken something, the old image is available at `0.5.5-0`. The new image is also available at `0.5.5-1` if you need to ensure you're not using a cached version of `0.5.5`.
