### ISSUE TITLE
Exporter showing lag for kafka topics which do not actually have lag

### ISSUE THREAD

**Issue by tarun-asthana** [braedon/prometheus-kafka-consumer-group-exporter#42]
Hi! I am using braedon/prometheus-kafka-consumer-group-exporter:0.5.5 image for my exporter deployed in kubernetes while my kafka brokers are on EC2. Could you explain what can cause this problem of false lag in metrics .

**Comment by braedon** [comment]
Hi @tarun-asthana, can you provide more information about the issue?

**Comment by har5ha-reddy** [comment]
Hi @braedon,

We are using the function **_kafka_consumer_group_lag_** to get the lag of a given consumer group. But the observation is that the value given by this function is actually different for the value obtained using the following shell script provided by kafka.

**_kafka-consumer-groups.sh --new-consumer --bootstrap-server localhost:9092 --describe --group group_name_**

And in all the cases, we found that the value returned by the kafka exporter is incorrect and the value returned by shell script was correct. Can you help us figure out the issue and suggest a possible solution if any ?

**Comment by braedon** [comment]
How much larger is the `kafka_consumer_group_lag` than the actual value? Does the exporter lag continue to grow over time, or is the lag relatively steady? Or does it grow for a period and then drop, before starting to grow again (if so, what's the period between drops?).

What does the actual lag look like? Are your consumers generally keeping up with the topics, or do they actually have significant lag (just not as much as the exporter indicates)?

`kafka_consumer_group_lag` is essentially `kafka_topic_highwater - kafka_consumer_group_offset`. Is `kafka_topic_highwater` updating correctly? Is `kafka_consumer_group_offset` correct, or does it similarly show consumers are further behind than they actually are?

`kafka_consumer_group_offset` is determined by consuming the `__consumer_offsets` topic. Is the exporter keeping up with updates to `__consumer_offsets`, or does `kafka_consumer_group_exporter_lag` indicate it's falling behind?

If you can post graphs of `kafka_consumer_group_lag`, `kafka_topic_highwater`, `kafka_consumer_group_offset`, and `kafka_consumer_group_exporter_lag` over time (e.g. 1 hour) it'd help with diagnosing the issue. Screenshots of graphs from the Prometheus interface would be fine.

**Comment by YanamadalaJaiPrakash** [comment]
Hi @braedon ,
The lag is `continuously increasing`.
The `actual lag is very low in single digits per partition` (keeping up with the topic), whereas the `lag from the exporter is in triple digits`.
We have checked `kafka_consumer_group_offset `, and this `value is higher than when we check the value on Kafka CLI`.
We have not checked the values of kafka_topic_highwater , i will check it and also post the graphs required.

**Comment by braedon** [comment]
Thanks for those details.

My best guess at this point is that the exporter isn't keeping up with the `__consumer_offsets` topic, resulting in old `kafka_consumer_group_offset` values. This would make it look like your consumers are lagging, when it's actually the exporter's consumer that is lagging.

If that's the case, you should see a high `kafka_consumer_group_exporter_lag`, and it should increase over time as the exporter gets more and more behind.

If the exporter doesn't have enough resources, it may not be able to consume `__consumer_offsets` fast enough. Check it's not maxing out CPU, or running out of memory.

I've also seen this happen when consumers are committing their offsets too often, flooding the `__consumer_offsets` topic. Check how fast `__consumer_offsets` is growing in `kafka_topic_highwater`. If any of your consumers commit after consuming each message, I'd recommend switching to committing periodically (e.g. every N messages, or at regular time intervals). Reducing the commit frequency will help the exporter keep up, and speed up your consumers/Kafka as well.

Alternatively, there could be some error preventing the exporter from consuming `__consumer_offsets`. Check if `kafka_consumer_group_exporter_offset` is actually increasing.

**Comment by braedon** [comment]
Hi folks, can you confirm if you've resolved the issue?

**Comment by monikaYadv** [comment]
@braedon : We also had similar issue in our setup. 

On checking further we identified exporter is running with 10% of resources consumption. kafka_topic_highwater is correct and keeping up to date. kafka_consumer_group_offset is not updating with correct current-offset and showing ever increasing lag.
What could have been the issue?

Is there any way we can speed exporter by using more parallelism like  1)  increasing the no of threads 2) or increasing the number of topic __consumer_offsets partitions or 3) increasing no of consumers for topic __consumer_offsets

**Comment by braedon** [comment]
Hi @monikaYadv, to help pin down exactly what is happening, please confirm:

1. If `kafka_consumer_group_exporter_lag` is high/increasing.
2. The number of active consumers you have committing offsets.
3. The commit frequency of your consumers.
