### ISSUE TITLE
The exporter seems to be unable to check all groups

### ISSUE THREAD

**Issue by lordgordon** [braedon/prometheus-kafka-consumer-group-exporter#43]
I'm running this tool in production but I recently noticed that the are missing lags for some groups. We are running the latest release.

In fact, checking `kafka_consumer_group_lag` I see the number of groups is below the expected value (about 20 less).
 
When querying Prometheus with `count by (topic) (kafka_consumer_group_exporter_lag)` we obtain a value between 20 and 30, well below the 50 partitions of `__consumer_offsets` topics.

At startup of `prometheus-kafka-consumer-group-exporter` I see all partitions are correctly assigned:
```
kafka.consumer.subscription_state.INFO MainThread Updated partition assignment: 
[TopicPartition(topic='__consumer_offsets', partition=0), 
TopicPartition(topic='__consumer_offsets', partition=1), 
...
TopicPartition(topic='__consumer_offsets', partition=48), 
TopicPartition(topic='__consumer_offsets', partition=49)]
```

Do you have any idea on how to fix this?

**Comment by lordgordon** [comment]
It seems that `--from-start` saved the day. I guess for the reason explained in this comment: https://github.com/braedon/prometheus-kafka-consumer-group-exporter/issues/17#issuecomment-421480548

**Comment by braedon** [comment]
Hi @lordgordon, does `--from-start` fully solve your issue?

**Comment by lordgordon** [comment]
@braedon yes. With that change we now have all groups and partitions, and everything works fine.

**Comment by braedon** [comment]
Great to hear. I'll close this issue then.
