### ISSUE TITLE
Kafka offset lags

### ISSUE THREAD

**Issue by panda87** [braedon/prometheus-kafka-consumer-group-exporter#8]
Hi

I know that you mentioned that, but since i'm not using this project with Prometheus backend but InfluxDB & Telegraf for metrics collector, i'm not able to run the function that calculate the lag.

Cab you pls try and calculate the lag according the function you mentioned in the README file during the http query?

Thanks
D.

**Comment by braedon** [comment]
@panda87 working on this. Should be included in the next release.

**Comment by panda87** [comment]
Great @braedon! Thanks

**Comment by braedon** [comment]
@panda87 this has been released in [0.3.0](https://github.com/braedon/prometheus-kafka-consumer-group-exporter/releases/tag/0.3.0)

**Comment by panda87** [comment]
That's amazing! thanks!
